from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import List
import hashlib
import subprocess

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import PP_PLACEHOLDER

from .models import EditInstruction, OutlineSlide, PptDocument, ShapeText, SlideContent


@dataclass
class ThemeConfig:
    name: str
    title_color: RGBColor
    body_color: RGBColor
    bg_color: RGBColor
    font_name: str
    title_size_pt: int
    body_size_pt: int


class PPTService:
    def parse_ppt(self, path: str) -> PptDocument:
        prs = Presentation(path)
        slides: List[SlideContent] = []

        for si, slide in enumerate(prs.slides):
            parsed = SlideContent(slide_index=si, shapes=[])
            for hi, shape in enumerate(slide.shapes):
                if not hasattr(shape, "text"):
                    continue
                text = (shape.text or "").strip()
                if not text:
                    continue
                role = self._shape_role(shape)
                if role == "title" and not parsed.title:
                    parsed.title = text
                parsed.shapes.append(ShapeText(shape_index=hi, role=role, text=text))
            slides.append(parsed)

        return PptDocument(path=path, slide_count=len(prs.slides), slides=slides)

    def apply_edits(self, path: str, edits: List[EditInstruction], output_path: str | None = None) -> str:
        prs = Presentation(path)
        for edit in edits:
            slide = prs.slides[edit.slide_index]
            shape = slide.shapes[edit.shape_index]
            if hasattr(shape, "text"):
                shape.text = edit.new_text

        # Re-apply inferred theme after text edits so color/font style is not lost
        # when certain PPT text boxes reset run formatting.
        theme = self.infer_theme_for_presentation(prs)
        self.apply_theme_to_presentation(prs, theme)

        save_path = output_path or self._default_output(path, "edited")
        prs.save(save_path)
        return save_path

    def create_from_outline(self, outline: List[OutlineSlide], output_path: str, topic: str, subtitle: str | None = None) -> str:
        prs = Presentation()

        cover = prs.slides.add_slide(prs.slide_layouts[0])
        cover.shapes.title.text = topic
        if len(cover.placeholders) > 1:
            cover.placeholders[1].text = subtitle or "Generated by ChatPPT"

        for item in outline:
            slide = prs.slides.add_slide(prs.slide_layouts[1])
            slide.shapes.title.text = item.title
            body = slide.shapes.placeholders[1].text_frame
            body.clear()
            bullets = item.bullets or ["Key point 1", "Key point 2"]
            for idx, bullet in enumerate(bullets):
                p = body.paragraphs[0] if idx == 0 else body.add_paragraph()
                p.text = bullet
                p.level = 0

        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        prs.save(output_path)
        return output_path

    def apply_theme(self, path: str, output_path: str | None = None) -> tuple[str, ThemeConfig]:
        prs = Presentation(path)
        theme = self.infer_theme_for_presentation(prs)
        self.apply_theme_to_presentation(prs, theme)

        save_path = output_path or self._default_output(path, f"theme-{theme.name}")
        prs.save(save_path)
        return save_path, theme

    def render_preview_images(self, path: str, preview_root: str) -> list[str]:
        src = Path(path)
        if not src.exists():
            raise FileNotFoundError(f"PPT not found: {path}")

        preview_root_path = Path(preview_root)
        digest = hashlib.sha1(str(src.resolve()).encode("utf-8")).hexdigest()[:12]
        out_dir = preview_root_path / digest
        out_dir.mkdir(parents=True, exist_ok=True)

        pdf_path = out_dir / f"{src.stem}.pdf"
        subprocess.run(
            [
                "soffice",
                "--headless",
                "--convert-to",
                "pdf",
                "--outdir",
                str(out_dir),
                str(src),
            ],
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )

        if not pdf_path.exists():
            candidate = out_dir / f"{src.stem}.PDF"
            if candidate.exists():
                pdf_path = candidate
        if not pdf_path.exists():
            raise RuntimeError("Failed to convert PPT to PDF for preview")

        prefix = out_dir / "slide"
        subprocess.run(
            ["pdftoppm", "-png", str(pdf_path), str(prefix)],
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )

        images = sorted(out_dir.glob("slide-*.png"))
        if not images:
            raise RuntimeError("No preview images generated")

        return [str(img.relative_to(preview_root_path)) for img in images]

    def infer_theme_for_presentation(self, prs: Presentation) -> ThemeConfig:
        full_text = " ".join(
            (shape.text or "")
            for slide in prs.slides
            for shape in slide.shapes
            if hasattr(shape, "text")
        ).lower()
        return self._theme_from_text(full_text)

    def infer_theme_from_outline(self, topic: str, outline: List[OutlineSlide]) -> ThemeConfig:
        text = " ".join([topic, *[s.title for s in outline], *[" ".join(s.bullets) for s in outline]])
        return self._theme_from_text(text.lower())

    def apply_theme_to_presentation(self, prs: Presentation, theme: ThemeConfig) -> None:
        for slide in prs.slides:
            fill = slide.background.fill
            fill.solid()
            fill.fore_color.rgb = theme.bg_color

            for shape in slide.shapes:
                if not hasattr(shape, "text_frame"):
                    continue
                role = self._shape_role(shape)
                for p in shape.text_frame.paragraphs:
                    for run in p.runs:
                        run.font.name = theme.font_name
                        if role == "title":
                            run.font.bold = True
                            run.font.size = self._pt(theme.title_size_pt)
                            run.font.color.rgb = theme.title_color
                        else:
                            run.font.size = self._pt(theme.body_size_pt)
                            run.font.color.rgb = theme.body_color

    def _shape_role(self, shape) -> str:
        try:
            if shape.is_placeholder:
                ptype = shape.placeholder_format.type
                if ptype == PP_PLACEHOLDER.TITLE or ptype == PP_PLACEHOLDER.CENTER_TITLE:
                    return "title"
                if ptype in (PP_PLACEHOLDER.BODY, PP_PLACEHOLDER.OBJECT):
                    return "body"
        except Exception:
            pass
        return "text"

    def _theme_from_text(self, text: str) -> ThemeConfig:
        if any(k in text for k in ["finance", "business", "strategy", "market", "企业", "商业"]):
            return ThemeConfig("corporate", RGBColor(12, 43, 89), RGBColor(30, 47, 64), RGBColor(239, 245, 252), "Calibri", 36, 20)
        if any(k in text for k in ["kids", "children", "fun", "game", "cartoon", "儿童", "趣味"]):
            return ThemeConfig("playful", RGBColor(154, 52, 142), RGBColor(52, 77, 160), RGBColor(255, 248, 230), "Arial", 40, 22)
        if any(k in text for k in ["tech", "ai", "code", "data", "cloud", "技术", "人工智能"]):
            return ThemeConfig("tech", RGBColor(22, 163, 74), RGBColor(15, 118, 110), RGBColor(240, 253, 250), "Segoe UI", 38, 20)
        return ThemeConfig("clean", RGBColor(17, 24, 39), RGBColor(55, 65, 81), RGBColor(249, 250, 251), "Calibri", 36, 20)

    def _default_output(self, path: str, suffix: str) -> str:
        src = Path(path)
        return str(src.with_name(f"{src.stem}_{suffix}{src.suffix}"))

    @staticmethod
    def _pt(size: int):
        from pptx.util import Pt

        return Pt(size)
